### ISSUE TITLE
Unstable tests in need of fixing

### ISSUE THREAD

**Issue by victorb** [ipfs/interface-js-ipfs-core#268]
```
  1) interface-ipfs-core tests,.files
       "after all" hook:
     Error: Uncaught AssertionError: The libp2p node is not started yet (webpack:///node_modules/assert/assert.js:195:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:18859)

  

  2) interface-ipfs-core tests,.dag
       "before all" hook:
     Uncaught TypeError: Cannot set property 'state' of undefined (node_modules/mocha/mocha.js:5143)

  

  3) interface-ipfs-core tests,.dag
       "before all" hook:
     TypeError: Cannot read property 'call' of undefined
    at ipfs.id (webpack:///node_modules/interface-ipfs-core/js/src/dag.js:35:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:293100:13)
    at setImmediate (webpack:///src/core/components/id.js:14:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:259514:24)
    at webpack:///node_modules/async/internal/setImmediate.js:27:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:82322:16
    at run (webpack:///node_modules/setimmediate/setImmediate.js:40:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:101788:13)
```

From: https://ci.ipfs.team/blue/rest/organizations/jenkins/pipelines/IPFS/pipelines/js-ipfs/branches/master/runs/105/nodes/15/steps/171/log/?start=0

The tests only failed on macOS, so the tests work, but just not this time.

To make these tests less unstable we should:
- Figure out a way of structuring the tests so they can't fail this way
- Or, if this is impossible, add a `this.retries(3)` and increase timeout.

**Comment by achingbrain** [comment]
Our tests have been a lot more stable since this issue was opened, let's keep an eye on any that fail repeatedly but I'm going to close this as the originally reported issue doesn't appear to exist any more.
